version: "3.2"

services:
  database:
    image: mysql:5.7
    volumes:
      - ./../db:/var/lib/mysql
    ports:
      - 3006:3306
    environment:
      - MYSQL_DATABASE=adonis
      - MYSQL_USER=toor
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: toor
      PMA_PASSWORD: 1234
    ports:
      - '8081:80'