version: "3.2"

services:
  database:
    image: mysql:5.7
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=adonis